// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJjRgND6rbnmVwiOjjGUq6ZCyVHrQoIqk',
    appId: '1:329032001640:web:4f8f86eb75acb706aeb3dd',
    messagingSenderId: '329032001640',
    projectId: 'game-a0dfd',
    authDomain: 'game-a0dfd.firebaseapp.com',
    storageBucket: 'game-a0dfd.firebasestorage.app',
    measurementId: 'G-D910XG4RL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCloJQxR63ZHLAFmO7mboQc5P3WRpd6_wk',
    appId: '1:329032001640:android:853c5f444bdff618aeb3dd',
    messagingSenderId: '329032001640',
    projectId: 'game-a0dfd',
    storageBucket: 'game-a0dfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQWQRl5qVKXOGIPOOl4rL0PSHziXfFsXc',
    appId: '1:329032001640:ios:dfe0c5044d17cd4aaeb3dd',
    messagingSenderId: '329032001640',
    projectId: 'game-a0dfd',
    storageBucket: 'game-a0dfd.firebasestorage.app',
    iosClientId: '329032001640-9dhscvi8833k12drril4hoemvi4veucr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tttGame',
  );

}